name: Build

on:
  push:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python development tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel setuptools-rust flake8 nose

      - name: Run clippy
        run: cargo clippy

      - name: Run flake8
        run: python -m flake8 nlplease tests

      - name: Run setup.py
        run: python setup.py develop

      - name: Run unit tests
        run: nosetests

